/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as TradesRouteImport } from './routes/trades'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRpcRouteImport } from './routes/api/rpc'
import { Route as ApiDexscreenerRouteImport } from './routes/api/dexscreener'
import { Route as ApiRugcheckMintRouteImport } from './routes/api/rugcheck.$mint'
import { Route as ApiJupiterSwapRouteImport } from './routes/api/jupiter/swap'
import { Route as ApiJupiterQuoteRouteImport } from './routes/api/jupiter/quote'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesRoute = TradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcRoute = ApiRpcRouteImport.update({
  id: '/api/rpc',
  path: '/api/rpc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDexscreenerRoute = ApiDexscreenerRouteImport.update({
  id: '/api/dexscreener',
  path: '/api/dexscreener',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRugcheckMintRoute = ApiRugcheckMintRouteImport.update({
  id: '/api/rugcheck/$mint',
  path: '/api/rugcheck/$mint',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJupiterSwapRoute = ApiJupiterSwapRouteImport.update({
  id: '/api/jupiter/swap',
  path: '/api/jupiter/swap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJupiterQuoteRoute = ApiJupiterQuoteRouteImport.update({
  id: '/api/jupiter/quote',
  path: '/api/jupiter/quote',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/logs': typeof LogsRoute
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/trades': typeof TradesRoute
  '/watchlist': typeof WatchlistRoute
  '/api/dexscreener': typeof ApiDexscreenerRoute
  '/api/rpc': typeof ApiRpcRoute
  '/api/jupiter/quote': typeof ApiJupiterQuoteRoute
  '/api/jupiter/swap': typeof ApiJupiterSwapRoute
  '/api/rugcheck/$mint': typeof ApiRugcheckMintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/logs': typeof LogsRoute
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/trades': typeof TradesRoute
  '/watchlist': typeof WatchlistRoute
  '/api/dexscreener': typeof ApiDexscreenerRoute
  '/api/rpc': typeof ApiRpcRoute
  '/api/jupiter/quote': typeof ApiJupiterQuoteRoute
  '/api/jupiter/swap': typeof ApiJupiterSwapRoute
  '/api/rugcheck/$mint': typeof ApiRugcheckMintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/logs': typeof LogsRoute
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/trades': typeof TradesRoute
  '/watchlist': typeof WatchlistRoute
  '/api/dexscreener': typeof ApiDexscreenerRoute
  '/api/rpc': typeof ApiRpcRoute
  '/api/jupiter/quote': typeof ApiJupiterQuoteRoute
  '/api/jupiter/swap': typeof ApiJupiterSwapRoute
  '/api/rugcheck/$mint': typeof ApiRugcheckMintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/logs'
    | '/safety'
    | '/settings'
    | '/trades'
    | '/watchlist'
    | '/api/dexscreener'
    | '/api/rpc'
    | '/api/jupiter/quote'
    | '/api/jupiter/swap'
    | '/api/rugcheck/$mint'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/logs'
    | '/safety'
    | '/settings'
    | '/trades'
    | '/watchlist'
    | '/api/dexscreener'
    | '/api/rpc'
    | '/api/jupiter/quote'
    | '/api/jupiter/swap'
    | '/api/rugcheck/$mint'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/logs'
    | '/safety'
    | '/settings'
    | '/trades'
    | '/watchlist'
    | '/api/dexscreener'
    | '/api/rpc'
    | '/api/jupiter/quote'
    | '/api/jupiter/swap'
    | '/api/rugcheck/$mint'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  LogsRoute: typeof LogsRoute
  SafetyRoute: typeof SafetyRoute
  SettingsRoute: typeof SettingsRoute
  TradesRoute: typeof TradesRoute
  WatchlistRoute: typeof WatchlistRoute
  ApiDexscreenerRoute: typeof ApiDexscreenerRoute
  ApiRpcRoute: typeof ApiRpcRoute
  ApiJupiterQuoteRoute: typeof ApiJupiterQuoteRoute
  ApiJupiterSwapRoute: typeof ApiJupiterSwapRoute
  ApiRugcheckMintRoute: typeof ApiRugcheckMintRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades': {
      id: '/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof TradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc': {
      id: '/api/rpc'
      path: '/api/rpc'
      fullPath: '/api/rpc'
      preLoaderRoute: typeof ApiRpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dexscreener': {
      id: '/api/dexscreener'
      path: '/api/dexscreener'
      fullPath: '/api/dexscreener'
      preLoaderRoute: typeof ApiDexscreenerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rugcheck/$mint': {
      id: '/api/rugcheck/$mint'
      path: '/api/rugcheck/$mint'
      fullPath: '/api/rugcheck/$mint'
      preLoaderRoute: typeof ApiRugcheckMintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jupiter/swap': {
      id: '/api/jupiter/swap'
      path: '/api/jupiter/swap'
      fullPath: '/api/jupiter/swap'
      preLoaderRoute: typeof ApiJupiterSwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jupiter/quote': {
      id: '/api/jupiter/quote'
      path: '/api/jupiter/quote'
      fullPath: '/api/jupiter/quote'
      preLoaderRoute: typeof ApiJupiterQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  LogsRoute: LogsRoute,
  SafetyRoute: SafetyRoute,
  SettingsRoute: SettingsRoute,
  TradesRoute: TradesRoute,
  WatchlistRoute: WatchlistRoute,
  ApiDexscreenerRoute: ApiDexscreenerRoute,
  ApiRpcRoute: ApiRpcRoute,
  ApiJupiterQuoteRoute: ApiJupiterQuoteRoute,
  ApiJupiterSwapRoute: ApiJupiterSwapRoute,
  ApiRugcheckMintRoute: ApiRugcheckMintRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
